vsphereprovider:
  datacenter: datacenter-stage
  datastore: datastore-stage
  disksizegib: 25
  folder: folder-stage
  memorymib: 16384
  network:
    dnsservers:
    - dnsServer-stage
    gateway: gateway-stage
    ipaddressprefix: ipAddressPrefix-stage
    k8snodeippoolend: nodeIpPoolEnd-stage
    k8snodeippoolstart: nodeIpPoolStart-stage
    segment: VmNetwork-stage
  numcpus: 4
  resourcepool: resourcePool-stage
