blank_issues_enabled: false
contact_links:
  - name: I have an idea/suggestion.
    url: https://github.com/microsoft/azure_arc/discussions/new?category=ideas
    about: Please submit your ideas here.
  - name: I have a question.
    url: https://github.com/microsoft/azure_arc/discussions/new?category=q-a
    about: Please ask and answer questions here.
#   - name: Getting Started Guide
#     url: https://jumpstart.azure.com/getting-started/
#     about: Get started with Azure Arc using Jumpstart
#   - name: ArcBox for IT Pros Troubleshooting
#     url: https://jumpstart.azure.com/azure_jumpstart_arcbox/ITPro/#basic-troubleshooting
#     about: Troubleshooting guide for ArcBox IT Pro scenarios
#   - name: ArcBox for DevOps Troubleshooting
#     url: https://jumpstart.azure.com/azure_jumpstart_arcbox/DevOps/#basic-troubleshooting
#     about: Troubleshooting guide for ArcBox DevOps scenarios
#   - name: ArcBox for DataOps Troubleshooting
#     url: https://jumpstart.azure.com/azure_jumpstart_arcbox/DataOps/#basic-troubleshooting
#     about: Troubleshooting guide for ArcBox DataOps scenarios
#   - name: HCIBox Troubleshooting
#     url: https://jumpstart.azure.com/azure_jumpstart_hcibox/troubleshooting
#     about: Troubleshooting guide for HCIBox deployment and operations
#   - name: Agora - Contoso Supermarket Troubleshooting
#     url: https://jumpstart.azure.com/azure_jumpstart_ag/contoso_supermarket/troubleshooting
#     about: Troubleshooting guide for Contoso Supermarket deployment
#   - name: Agora - Contoso Motors Troubleshooting
#     url: https://jumpstart.azure.com/azure_jumpstart_ag/contoso_motors/troubleshooting
#     about: Troubleshooting guide for Contoso Motors deployment
#   - name: Agora - Contoso Hypermarket Troubleshooting
#     url: https://jumpstart.azure.com/azure_jumpstart_ag/contoso_hypermarket/troubleshooting/
#     about: Troubleshooting guide for Contoso Hypermarket deployment
#   - name: Azure Arc GitHub Discussions
#     url: https://github.com/microsoft/azure_arc/discussions
#     about: Ask questions and discuss with the community
#   - name: Azure Arc Documentation
#     url: https://learn.microsoft.com/azure/azure-arc/
#     about: Microsoft Learn documentation for Azure Arc
#   - name: Azure Local Documentation
#     url: https://learn.microsoft.com/azure/azure-local/
#     about: Microsoft Learn documentation for Azure Local
