{{ define "patch-controller-rs-hook" }}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: patch-controller-rs-job
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-upgrade, post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - command:
        - /opt/bootstrapper/bin/bootstrapper
        - -bootstrap
        - -patchReplicaSet
        - -namespace
        - {{ .Release.Namespace }}
        - -image
        - {{ .Values.systemDefaultValues.image }}
        image: {{ .Values.systemDefaultValues.image }}
        name: bootstrapper
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      imagePullSecrets:
      - name: {{ .Values.systemDefaultValues.imagePullSecret }}
      restartPolicy: Never
      serviceAccountName: {{ include "installerServiceAccount" . | default "sa-arc-bootstrapper" }}
  backoffLimit: 4
{{ end }}


{{ $dataControllerCRD := (lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "datacontrollers.arcdata.microsoft.com") }}
{{ if $dataControllerCRD }}

# This is only applicable for clusters running GA version
{{ $dataControllerCRs := (lookup "arcdata.microsoft.com/v1" "DataController" .Release.Namespace "") }}
{{ if $dataControllerCRs }}
{{ if $dataControllerCRs.items }}

{{ if (and (contains "v1.0.0" (get (index $dataControllerCRs.items 0).spec.docker "imageTag")) (not (contains "v1.0.0" "{{ .Values.systemDefaultValues.image }}"))) }}

{{- include "patch-controller-rs-hook" . }}

{{ end }}
{{ end }}
{{ end }}
{{ end }}
