#
# This file contains sample RoleBindings for Azure Arc enabled data services that uses Roles.
#
# This rolebinding grants permission to the user based on the azure-arc-data:reader role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azure-arc-data:readers
  #
  # The namespace of the RoleBinding determines where the permissions are granted.
  # This only grants permissions within the "azure-arc-data" namespace.
  namespace: azure-arc-data
subjects:
- kind: User
  name: hr-user # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: azure-arc-data:reader
  apiGroup: rbac.authorization.k8s.io
---
# This rolebinding grants permission to the user based on the azure-arc-data:database-instance:reader role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azure-arc-data:database-instance:readers
  #
  # The namespace of the RoleBinding determines where the permissions are granted.
  # This only grants permissions within the "azure-arc-data" namespace.
  namespace: azure-arc-data
subjects:
- kind: User
  name: hr-user # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: azure-arc-data:database-instance:reader
  apiGroup: rbac.authorization.k8s.io
---
# This rolebinding grants permission to the user based on the azure-arc-data:data-controller:reader role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azure-arc-data:data-controller:readers
  #
  # The namespace of the RoleBinding determines where the permissions are granted.
  # This only grants permissions within the "azure-arc-data" namespace.
  namespace: azure-arc-data
subjects:
- kind: User
  name: hr-user # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: azure-arc-data:data-controller:reader
  apiGroup: rbac.authorization.k8s.io
---
# This rolebinding grants permission to the user based on the sql-managed-instance:reader role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azure-arc-data:sql-managed-instance:readers
  #
  # The namespace of the RoleBinding determines where the permissions are granted.
  # This only grants permissions within the "azure-arc-data" namespace.
  namespace: azure-arc-data
subjects:
- kind: User
  name: hr-user # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: azure-arc-data:sql-managed-instance:reader
  apiGroup: rbac.authorization.k8s.io
---
# This rolebinding grants permission to the user based on the sql-managed-instance:reader role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azure-arc-data:postgresql-hyperscale:readers
  #
  # The namespace of the RoleBinding determines where the permissions are granted.
  # This only grants permissions within the "azure-arc-data" namespace.
  namespace: azure-arc-data
subjects:
- kind: User
  name: hr-user # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: azure-arc-data:postgresql-hyperscale:reader
  apiGroup: rbac.authorization.k8s.io
---


# This rolebinding grants permission to the user based on the azure-arc-data:writer role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azure-arc-data:writers
  #
  # The namespace of the RoleBinding determines where the permissions are granted.
  # This only grants permissions within the "azure-arc-data" namespace.
  namespace: azure-arc-data
subjects:
- kind: User
  name: hr-admin # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: azure-arc-data:writer
  apiGroup: rbac.authorization.k8s.io
---
# This rolebinding grants permission to the user based on the azure-arc-data:database-instance:writer role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azure-arc-data:database-instance:writers
  #
  # The namespace of the RoleBinding determines where the permissions are granted.
  # This only grants permissions within the "azure-arc-data" namespace.
  namespace: azure-arc-data
subjects:
- kind: User
  name: hr-admin # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: azure-arc-data:database-instance:writer
  apiGroup: rbac.authorization.k8s.io
---
# This rolebinding grants permission to the user based on the azure-arc-data:data-controller:writer role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azure-arc-data:data-controller:writers
  #
  # The namespace of the RoleBinding determines where the permissions are granted.
  # This only grants permissions within the "azure-arc-data" namespace.
  namespace: azure-arc-data
subjects:
- kind: User
  name: hr-admin # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: azure-arc-data:data-controller:writer
  apiGroup: rbac.authorization.k8s.io
---
# This rolebinding grants permission to the user based on the sql-managed-instance:writer role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azure-arc-data:sql-managed-instance:writers
  #
  # The namespace of the RoleBinding determines where the permissions are granted.
  # This only grants permissions within the "development" namespace.
  namespace: azure-arc-data
subjects:
- kind: User
  name: hr-admin # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: azure-arc-data:sql-managed-instance:writer
  apiGroup: rbac.authorization.k8s.io
---
# This rolebinding grants permission to the user based on the sql-managed-instance:writer role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azure-arc-data:postgresql-hyperscale:writers
  #
  # The namespace of the RoleBinding determines where the permissions are granted.
  # This only grants permissions within the "development" namespace.
  namespace: azure-arc-data
subjects:
- kind: User
  name: hr-admin # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: azure-arc-data:postgresql-hyperscale:writer
  apiGroup: rbac.authorization.k8s.io
