apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/releases/download/CLUSTERCTL_VERSION/cluster-template.yaml
patchesStrategicMerge:
- patches/Cluster.yaml
- patches/KubeadmControlPlane.yaml
- patches/AzureCluster.yaml