apiVersion: v1
kind: SecurityContextConstraints
metadata:
  name: arc-data-scc
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities:
  - SETUID
    SETGID
    CHOWN
    SYS_PTRACE
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
readOnlyRootFilesystem: false
requiredDropCapabilities:
  - KILL
    MKNOD
runAsUser:
  type: MustRunAsNonRoot
seLinuxContext:
  type: MustRunAsNonRoot
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
    downwardAPI
    emptyDir
    persistentVolumeClaim
    projected
    secret