apiVersion: v1
data:
  password: <your base64 encoded password>
kind: Secret
metadata:
  name: example-login-secret
type: Opaque
---
apiVersion: arcdata.microsoft.com/v1alpha1
kind: postgresql-12
metadata:
  generation: 1
  name: example
spec:
  engine:
    extensions:
    - name: citus
  scale:
    watchers: 3
  scheduling:
    default:
      resources:
        limits:
          cpu: "4"
          memory: 4Gi
        requests:
          cpu: "1"
          memory: 2Gi
  service:
    type: LoadBalancer # Modify service type based on your Kubernetes environment
  storage:
    backups:
      className: default # Use default configured storage class or modify storage class based on your Kubernetes environment
      size: 5Gi
    data:
      className: default # Use default configured storage class or modify storage class based on your Kubernetes environment
      size: 5Gi
    logs:
      className: default # Use default configured storage class or modify storage class based on your Kubernetes environment
      size: 1Gi
