apiVersion: batch/v1
kind: Job
metadata:
  name: arc-uninstall-job
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: bootstrapper
        image: mcr.microsoft.com/arcdata/arc-bootstrapper:v1.27.0_2024-02-13
        imagePullPolicy: IfNotPresent
        args: ["-uninstall"]
        command: ["/opt/bootstrapper/bin/bootstrapper"]
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      imagePullSecrets:
      - name: arc-private-registry
      restartPolicy: Never
      serviceAccountName: sa-arcdata-deployer #optional
  ttlSecondsAfterFinished: 86400 #24 hours
  backoffLimit: 0
